stages:
  install_deps:
    cmd: pip install -r requirements.txt
    deps:
      - requirements.txt
  download_hf_imdb:
    #cmd: python src/stages/download_hf_imdb.py --config=params.yaml
    cmd: export PYTHONPATH=$PYTHONPATH:$(pwd) && python src/stages/download_hf_imdb.py --config=params.yaml
    deps:
    - src/stages/download_hf_imdb.py
    #- src/pipelines/download_hf_imdb.py
    params:
    - download_hf_imdb
    outs:
    - data/raw/imdb
#######
  train_reward:
    cmd: export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" && export PYTHONPATH=$PYTHONPATH:$(pwd) && python src/stages/train_reward_model.py --config=params.yaml
    deps:
    - src/stages/train_reward_model.py
    #- src/pipelines/train_reward.py
    params:
    - train_reward
    outs:
    - models/reward_model # НЕ ПРОВЕРЯЛ 
######
  train_gpt:
    cmd:
    deps:
    - src/stages/train_gpt.py
    params:
    - train_gpt
    outs:
    - models/gpt
